#!bin/sh
brew reinstall abstract
brew reinstall adobe-acrobat-reader
brew reinstall adobe-creative-cloud
brew reinstall android-studio
brew reinstall appcleaner
brew reinstall barrier
brew reinstall bettertouchtool
brew reinstall betterzipql
brew reinstall discord
brew reinstall docker
brew reinstall dropbox
brew reinstall figma
brew reinstall filezilla
brew reinstall findergo
brew reinstall firefox-developer-edition
brew reinstall go64
brew reinstall google-chrome
brew reinstall google-japanese-ime
brew reinstall handbrake
brew reinstall iterm2
brew reinstall keka
brew reinstall macforge
brew reinstall mapture
brew reinstall miro
brew reinstall obs
brew reinstall qlcolorcode
brew reinstall qlmarkdown
brew reinstall qlstephen
brew reinstall quicklook-json
brew reinstall razer-synapse
brew reinstall sidequest
brew reinstall sketch
brew reinstall splashtop-personal
brew reinstall toggl
brew reinstall unity
brew reinstall virtualhere
brew reinstall virtualhereserver
brew reinstall visual-studio-code
brew reinstall vlc
brew reinstall whoozle-android-file-transfer
brew reinstall zoomus
