#!bin/sh
brew install --cask iterm2
brew install --cask google-japanese-ime
brew install --cask adobe-reader
brew install --cask docker
brew install --cask google-chrome
brew install --cask betterzipql
brew install --cask visual-studio-code
brew install --cask firefox
brew install --cask java
brew install --cask figma
brew install --cask zoomus
brew install --cask sketch
brew install --cask bettertouchtool
brew install --cask whoozle-android-file-transfer
brew install --cask android-studio
brew install --cask splashtop-personal
brew install --cask keka
brew install --cask discord
brew install --cask sidequest
brew install --cask virtualhere
brew install --cask virtualhereserver
brew install --cask handbrake
brew install --cask abstract
brew install --cask barrier
brew install --cask vlc
brew install --cask unity
brew install --cask handbrake
brew install --cask dropbox
brew install --cask miro
brew install --cask adobe-creative-cloud
