#!bin/sh
brew install --cask 1password
brew install --cask abstract
brew install --cask adobe-acrobat-reader
brew install --cask adobe-creative-cloud
brew install --cask android-studio
brew install --cask appcleaner
brew install --cask barrier
brew install --cask bettertouchtool
brew install --cask discord
brew install --cask docker
brew install --cask dropbox
brew install --cask figma
brew install --cask filezilla
brew install --cask findergo
brew install --cask firefox-developer-edition
brew install --cask go64
brew install --cask google-chrome
brew install --cask google-japanese-ime
brew install --cask handbrake
brew install --cask iterm2
brew install --cask keka
brew install --cask macforge
brew install --cask miro
brew install --cask obs
brew install --cask razer-synapse
brew install --cask sidequest
brew install --cask sketch
brew install --cask splashtop-personal
brew install --cask unity
brew install --cask virtualhere
brew install --cask virtualhereserver
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask zoomus
